server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:products}
    username: PruebaTecnica
    password: PRTEC10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  api-key: API_KEY_PRODUCTS_123

