server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:inventario}
    username: PruebaTecnica
    password: PRTEC10
  jpa:
    hibernate:
      ddl-auto: update

products:
  url: http://products-service:8081

security:
  api-key: API_KEY_INVENTORY_456
